# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "807095145857452f21cb4442a45a651b"
application_url = "https://bulkapp.omni-sync.com"
embedded = true
name = "Sku & Barcode Generator"
handle = "bulkapp-4"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "wixpa-task.myshopify.com"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_assigned_fulfillment_orders,read_checkouts,read_content,read_draft_orders,read_files,read_fulfillments,read_inventory,read_locales,read_locations,read_markets,read_online_store_navigation,read_online_store_pages,read_orders,read_product_listings,read_themes,read_third_party_fulfillment_orders,read_translations,unauthenticated_read_content,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,write_assigned_fulfillment_orders,write_content,write_draft_orders,write_files,write_fulfillments,write_locales,write_markets,write_orders,write_products,write_themes,write_third_party_fulfillment_orders,write_translations,write_inventory"


[auth]
redirect_urls = [
  "https://bulkapp.omni-sync.com/authenticate"
]

[pos]
embedded = false
